version: '3'

services:
    brevets:
        build: brevets/.
        command: python3 flask_brevets.py
        ports: 
          - "5001:5000"
        depends_on:
          - redis
    redis:
      image: redis
